[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.install]
cmds = [
    "python3.11 -m venv /opt/venv",
    "source /opt/venv/bin/activate && pip install --upgrade pip setuptools wheel",
    "source /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Python app built successfully'"]

[start]
cmd = "source /opt/venv/bin/activate && python3.11 api_server.py"

[variables]
PYTHON_VERSION = "3.11" 
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1" 