[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "python3Packages.virtualenv"]

[phases.install]
cmds = [
    "python3 -m venv /opt/venv",
    "source /opt/venv/bin/activate && pip install --upgrade pip",
    "source /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Python app built successfully'"]

[start]
cmd = "source /opt/venv/bin/activate && python3 api_server.py" 